[build]
builder = "nixpacks"
buildCommand = "cd cms && npm ci && npm run build"

[deploy]
startCommand = "cd cms && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 30 