[build]
builder = "nixpacks"
buildCommand = "cd cms && npm ci && npm run build"

[deploy]
startCommand = "cd cms && npm run start"
healthcheckPath = "/health"
healthcheckPort = "8080"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[deploy.healthcheck]
path = "/api/health"
interval = "45s"
timeout = "15s"
retries = 5
grace_period = "120s" 