[build]
builder = "nixpacks"
buildCommand = "cd cms && npm ci && npm run build"

[deploy]
startCommand = "cd cms && npm run start"
healthcheckPath = "/admin"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 