[build]
builder = "nixpacks"
buildCommand = "cd cms && npm ci && npm run build"

[deploy]
startCommand = "cd cms && npm run start"
healthcheckPath = "/health"
healthcheckPort = "8080"
healthcheckTimeout = 60
restartPolicyType = "on_failure" 