[build]
builder = "nixpacks"
buildCommand = "cd cms && npm ci && npm run build"

[deploy]
startCommand = "cd cms && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 180
healthcheckInterval = 45
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/api/health"
interval = "45s"
timeout = "15s"
retries = 5
grace_period = "120s" 