[build]
provider = "node"
buildCommand = """
cd cms &&
pwd && ls -la && 
echo 'Installing dependencies...' && 
npm ci && 
echo 'Verifying installation...' &&
ls -la node_modules/.bin &&
echo 'Building Strapi...' && 
NODE_ENV=production ./node_modules/.bin/strapi build &&
echo 'Initializing database...' && 
NODE_ENV=production ./node_modules/.bin/strapi database:rebuild --force
"""

[deploy]
startCommand = """
cd cms &&
pwd && ls -la &&
echo 'Verifying Strapi installation...' &&
ls -la node_modules/.bin &&
echo 'Starting Strapi...' &&
NODE_ENV=production DEBUG=strapi:* ./node_modules/.bin/strapi start
"""
healthcheckPath = "/health"
healthcheckTimeout = 180
healthcheckInterval = 30
healthcheckInitialDelay = 60
restartPolicyType = "on-failure"
numReplicas = 1

[deploy.envVars]
NODE_ENV = "production"
APP_KEYS = "cRPK/MkWbI/ZNLNzhLt3Je31Io1gLv5lBOiRmLeBd9Y=,ezobJaE96ukIUSfOAZFS2Az2Vw4k4b++EX7NitxJ3ps=,MFpOkwqBElVXsn+GYVcq7FXoHJTojjgL8jQgfr+C7mw=,MMjs9W6W/onIaOt3Ds3xsot1kGaWCjrQd3kmsgtaPaU="
API_TOKEN_SALT = "ygEuGNwfBAq3GPeQpjKstKVT8556tMIOLIV/R/U42WY="
ADMIN_JWT_SECRET = "wuRmkv0+HqOihRD7T0AURwWZeMa7VmW1tYmT5A9BhhA="
JWT_SECRET = "thrg44QCdb45FYdK/0Sj83JGKanM5kN+DY5T4I0ifos=="
TRANSFER_TOKEN_SALT = "1nW+1dVsRYQOstzV7zRNNjOVc/wxSJi5RMzkQIF8uj8="
HOST = "0.0.0.0"
PORT = "1337"
DATABASE_CLIENT = "postgres"
DATABASE_SSL = "true"
PGHOST = "postgres.railway.internal"
PGPORT = "5432"
PGDATABASE = "railway"
PGUSER = "postgres"
PGPASSWORD = "BbIbbyQYmoGBsFuHpsbXjodevszruGtk" 