[build]
provider = "node"
buildCommand = """
cd cms &&
pwd && ls -la && 
echo 'Installing dependencies...' && 
npm ci && 
echo 'Building Strapi...' && 
npm run build && 
echo 'Initializing database...' && 
npx strapi database:rebuild --force
"""

[deploy]
startCommand = """
cd cms &&
pwd && ls -la &&
echo 'Starting Strapi...' &&
npx strapi start
"""
healthcheckPath = "/"
healthcheckTimeout = 180
healthcheckInterval = 15
healthcheckInitialDelay = 30
restartPolicyType = "on-failure"
numReplicas = 1

[deploy.envVars]
NODE_ENV = "production"
APP_KEYS = "testKey1,testKey2"
API_TOKEN_SALT = "testsalt"
ADMIN_JWT_SECRET = "testjwt"
JWT_SECRET = "testjwtsecret"
HOST = "0.0.0.0"
PORT = "1337" 