[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "NODE_ENV=production npm run start"
healthcheckPath = "/admin/login"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
numReplicas = 1

[nixpacks]
start-command = "NODE_ENV=production npm run start"

[deploy.envVars]
NODE_ENV = "production" 