[build]
provider = "node"
buildCommand = """
pwd && ls -la && 
echo 'Installing dependencies...' && 
npm ci && 
echo 'Building Strapi...' && 
npm run build && 
echo 'Initializing database...' && 
npm run strapi database:rebuild --force
"""

[deploy]
startCommand = "pwd && ls -la && cd cms && NODE_ENV=production npm run strapi start"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "on-failure"
numReplicas = 1

[deploy.envVars]
NODE_ENV = "production"
APP_KEYS = "testKey1,testKey2"
API_TOKEN_SALT = "testsalt"
ADMIN_JWT_SECRET = "testjwt"
JWT_SECRET = "testjwtsecret" 