[build]
provider = "node"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/admin"
healthcheckPort = 1337
healthcheckTimeout = 100
restartPolicyType = "on-failure"
numReplicas = 1

[deploy.envVars]
NODE_ENV = "production"
PORT = "1337" 