[build]
provider = "node"
buildCommand = """
cd cms &&
pwd && ls -la && 
echo 'Installing dependencies...' && 
npm ci && 
echo 'Verifying installation...' &&
ls -la node_modules/.bin &&
echo 'Building Strapi...' && 
NODE_ENV=production ./node_modules/.bin/strapi build &&
echo 'Initializing database...' && 
NODE_ENV=production ./node_modules/.bin/strapi database:rebuild --force
"""

[deploy]
startCommand = """
cd cms &&
pwd && ls -la &&
echo 'Verifying Strapi installation...' &&
ls -la node_modules/.bin &&
echo 'Starting Strapi...' &&
NODE_ENV=production DEBUG=strapi:* ./node_modules/.bin/strapi start
"""
healthcheckPath = "/health"
healthcheckTimeout = 180
healthcheckInterval = 30
healthcheckInitialDelay = 60
restartPolicyType = "on-failure"
numReplicas = 1

[deploy.envVars]
NODE_ENV = "production"
APP_KEYS = "testKey1,testKey2"
API_TOKEN_SALT = "testsalt"
ADMIN_JWT_SECRET = "testjwt"
JWT_SECRET = "testjwtsecret"
HOST = "0.0.0.0"
PORT = "1337"
DATABASE_CLIENT = "postgres"
DATABASE_SSL = "false" 