services:
  - type: web
    name: willtendy-cms
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.7
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: willtendy-db
          property: connectionString
